name: Update Major Version Tag
on:
  release:
    types: [published]

jobs:
  update-major-tag:
    runs-on: ubuntu-latest
    if: startsWith(github.event.release.tag_name, 'v1.')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update v1 tag
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git tag -f v1
          git push origin v1 -f